name: Deploy to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-and-deploy-production:
    name: Fetch image and deploy to production environment on merge to master branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker eu.gcr.io

      - name: Apply Helm template
        run: |
          helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
          helm fetch --untar --untardir ./helm fdk/dcat-ap-no-validator-cache
          helm template -f ./helm/dcat-ap-no-validator-cache/values/prod.yaml \
          ./helm/dcat-ap-no-validator-cache/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Setup gcloud CLI for snapshot & deploy
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
          export_default_credentials: true

      - name: Create backup snapshot
        run: |
          gcloud compute --project digdir-fdk-prod disks snapshot "fdk-prod-dcat-ap-no-validator-cache" --snapshot-names "autogcs-ad-prod-dcatapnoval-cache-${GITHUB_SHA::8}" --zone "europe-north1-a" &
          wait
          gcloud compute --project digdir-fdk-prod snapshots add-labels "autogcs-ad-prod-dcatapnoval-cache-${GITHUB_SHA::8}" --labels="snapshotdays="14""

      - name: Deploy to GCP & check status
        run: |
          gcloud container clusters get-credentials digdir-fdk-prod --region europe-north1-a --project digdir-fdk-prod
          kubectl apply -f ./kubectlapply.yaml --force
          if ! kubectl --namespace=prod rollout status deployment dcat-ap-no-validator-cache; then
          kubectl --namespace=prod rollout undo deployment dcat-ap-no-validator-cache
          kubectl --namespace=prod rollout status deployment dcat-ap-no-validator-cache
          exit 1
          fi

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: dcat-ap-no-validator-cache | Environment: prod'
          fields: commit,author,workflow,message
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Trigger deploy to demo
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: deploy-demo
          client-payload: '{"sha": "${{ github.sha }}"}'
